# ------------------------------------------------------------
# Cops that rubocop disables by default, but we want to enable
# ------------------------------------------------------------

Bundler/GemComment:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

# Lint/NumberConversion (prefer cast invalid numbers to 0 rather than throw)

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConstantVisibility:
  Enabled: true

Style/Copyright:
  Enabled: true
  Notice: 'Copyright \(c\) 2016 Scott O.Hara, oharagroup.net'

Style/DateTime:
  Enabled: true

# Style/DocumentationMethod (disabled due to no documentation)

Style/ImplicitRuntimeError:
  Enabled: true

# Style/InlineComment (disabled due to use of inline comments)

Style/IpAddresses:
  Enabled: true

# Style/MethodCallWithArgsParentheses (prefer no parens)

Style/MethodCalledOnDoEndBlock:
  Enabled: true

# Style/MissingElse (else not required)

Style/MultilineMethodSignature:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

# Style/StringHashKeys (disabled because JSON used heavily with string keys)

Style/StringMethods:
  Enabled: true

# ------------------------------------------------------------
# END disabled by default cops
# ------------------------------------------------------------
# Cops that rubocop enables by default, but we want to disable
# ------------------------------------------------------------

# Prefer tabs over spaces
Layout/Tab:
  Enabled: false

# Block comment in spec_helper
Style/BlockComments:
  Enabled: false

# Only require parens where absolutely necessary
Style/NestedParenthesizedCalls:
  Enabled: false

# Disable metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# ------------------------------------------------------------
# END enabled by default cops
# ------------------------------------------------------------
# Cops that we want to reconfigure
# ------------------------------------------------------------

# Changed from 2 (spaces) to 1 (tab)
Layout/IndentationWidth:
  Width: 1

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# ------------------------------------------------------------
# END reconfigured cops
# ------------------------------------------------------------
