AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true
  EnabledByDefault: true
  NewCops: enable

# Use consistent indentation for arrays even in method calls
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# Use consistent indentation for hashes even in method calls
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Prefer tabs over spaces
Layout/IndentationStyle:
  EnforcedStyle: tabs

# Use single tab for indentation
Layout/IndentationWidth:
  Width: 1

# Don't enforce max line length
Layout/LineLength:
  Enabled: false

# Don't allow spaces inside literal hash braces
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Prefer cast invalid numbers to 0 rather than throw
Lint/NumberConversion:
  Enabled: false

# Disable metrics department
Metrics:
  Enabled: false

# Allow block comment in spec_helper
Style/BlockComments:
  Enabled: false

# Prefer `class << self` to `self.method_name`
Style/ClassMethodsDefinitions:
  EnforcedStyle: self_class

Style/Copyright:
  Notice: 'Copyright \(c\) 2016 Scott O.Hara, oharagroup.net'

# Don't require documentation comment for public methods
Style/DocumentationMethod:
  Enabled: false

# Allow trailing inline comments
Style/InlineComment:
  Enabled: false

# Omit parens where possible
# TODO - check if we can leave this enabled and switch EnforcedStyle: omit_parentheses
Style/MethodCallWithArgsParentheses:
  Enabled: false

# Else not required
Style/MissingElse:
  Enabled: false

# Only require parens where absolutely necessary
Style/NestedParenthesizedCalls:
  Enabled: false

# Disabled because JSON used heavily with string keys
Style/StringHashKeys:
  Enabled: false