---
name: Release
on:
  release:
    types: published

permissions:
  contents: read
  id-token: write

concurrency: release

jobs:
  publish:
    name: Publish to rubygems
    runs-on: ubuntu-latest
    environment: rubygems registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install ruby and gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: gem build rubocop-config-oharagroup.gemspec

      - name: Publish
        run: gem push rubocop-config-oharagroup-*.gem
